QA_and_RAG:
  path: ${oc.env:WORKING_DIR}/QA_and_RAG
  chinook_db_path: ${.path}/data/sql/chinook.db
  stored_sql_db_path: ${.path}/data/flat_files/stored_data.db
  uploaded_files_path: ${.path}/data/for_upload
  uploaded_db_path: ${.uploaded_files_path}/db_path/uploaded_data.db

  llm:
    model: gpt-4o-mini
    temperature: 0.0

  sql_agent_prompt: |
    Given an input question, create a syntactically correct {dialect} query to run to help find the answer. Unless the user specifies in his question a specific number of examples they wish to obtain, always limit your query to at most {top_k} results. You can order the results by a relevant column to return the most interesting examples in the database.
    Never query for all the columns from a specific table, only ask for a the few relevant columns given the question.
    Pay attention to use only the column names that you can see in the schema description. Be careful to not query for columns that do not exist. Also, pay attention to which column is in which table.
    Only use the following tables:
    {table_info}

    Question: {input}
    
  encoder_model:
    model: all-MiniLM-L6-v2
    embedding_dimension: 384
