QA_and_RAG:
  path: QA_and_RAG
  chinook_db_path: sqlite:///${.path}/data/sql/chinook.db
  sql_agent_prompt: |
    Based on the database query result, provide a complete sentence answer to the user's question.

    Question: {question}
    SQL Result: {result}
    Answer:

  
